-- ==============================================================================
-- MASTER SKINS DATABASE (RGB + TT_S2 SNIPER THEMES)
-- Hosted externally on GitHub for V53 Modular Injector
-- ==============================================================================

return {
    PrimaryBases = {
        "AWP", "Crossbow", "DSR1", "Kar98k", "M200", "M82A1", "NTW20", "SSG", "Specter", "WA2000"
    },
    
    MeleeBases = {
        "Axe", "Bayonet", "Bayonet_M9", "Bowie", "ButterflyKnife", "ClassKnife", 
        "CordKnife", "CrookSword", "Falchion", "FlipKnife", "Glove", "GutKnife", 
        "Karambit", "Kukri", "OutDoorKnife", "ShadowDaggers", "Shovel", "Skeleton", 
        "Stiletto", "TacticalKnife", "Wakizashi"
    },
    
    PrimarySkins = {
        "Exotic.RGB.Apocalypse.AWP",
        "Exotic.RGB.Apocalypse.AWP.Exotic",
        "Exotic.RGB.Apocalypse.Specter",
        "Exotic.RGB.Apocalypse.Specter.Exotic",
        "Exotic.RGB.AWP.Exotic",
        "Exotic.RGB.Eternium.M200",
        "Exotic.RGB.Eternium.M200.Exotic",
        "Exotic.RGB.Eternium.SSG",
        "Exotic.RGB.Eternium.SSG.Exotic",
        "Exotic.RGB.Lumen.M82A1",
        "Exotic.RGB.Lumen.M82A1.Exotic",
        "Exotic.RGB.NeonCore.AWP",
        "Exotic.RGB.NeonCore.AWP.Exotic",
        "Exotic.RGB.NeonCore.Kar98k",
        "Exotic.RGB.NeonCore.Kar98k.Exotic",
        "Exotic.RGB.NeonCore.M82A1",
        "Exotic.RGB.NeonCore.M82A1.Exotic",
        "Exotic.RGB.NeonCore.SSG",
        "Exotic.RGB.NeonCore.SSG.Exotic",
        "Exotic.RGB.NightHunt.Crossbow.Exotic",
        "Exotic.RGB.Nya.AWP.Exotic",
        "Exotic.RGB.Nya.Kar98k.Exotic",
        "Exotic.RGB.Nya.M82A1.Exotic",
        "Exotic.RGB.Nya.Specter.Exotic",
        "Exotic.RGB.S4.VioletFiend.NTW20.Exotic",
        "Exotic.RGB.S5.VioletFiend.AWP.Exotic",
        "Exotic.RGB.S5.VioletFiend.M82A1.Exotic",
        "Exotic.RGB.SSG.Exotic",
        "Exotic.RGB.StarLord.DSR1.Exotic",
        "Exotic.RGB.StarLord.Kar98k.Exotic",
        "Exotic.RGB.Starry.AWP",
        "Exotic.RGB.Starry.AWP.Exotic",
        "Exotic.RGB.Starry.Crossbow",
        "Exotic.RGB.Starry.Crossbow.Exotic",
        "Exotic.RGB.Starry.DSR1",
        "Exotic.RGB.Starry.DSR1.Exotic",
        "Exotic.RGB.Starry.Kar98k",
        "Exotic.RGB.Starry.Kar98k.Exotic",
        "Exotic.RGB.Starry.M200",
        "Exotic.RGB.Starry.M200.Exotic",
        "Exotic.RGB.Starry.M82A1",
        "Exotic.RGB.Starry.M82A1.Exotic",
        "Exotic.RGB.Starry.NTW20",
        "Exotic.RGB.Starry.NTW20.Exotic",
        "Exotic.RGB.Starry.Specter.Exotic",
        "Exotic.RGB.Starry.SSG.Exotic",
        "Exotic.RGB.Starry.WA2000",
        "Exotic.RGB.Starry.WA2000.Exotic",
        "Exotic.RGB.Steam.M200",
        "Exotic.RGB.Steam.M200.Exotic",
        "Exotic.RGB.Steam.M82A1",
        "Exotic.RGB.Steam.M82A1.Exotic",
        "Exotic.RGB.TT_S2.Sniper1",
        "Exotic.RGB.TT_S2.Sniper1.Exotic",
        "Exotic.RGB.Watcher.AWP",
        "Exotic.RGB.Watcher.AWP.Exotic",
        "Exotic.RGB.Watcher.M82A1",
        "Exotic.RGB.Watcher.M82A1.Exotic",
        
        -- [TT_S2 SNIPER THEMES ADDED BELOW] --
        "Exotic.TT_S2.Sniper1",
        "Exotic.TT_S2.Sniper1.Exotic",
        "Exotic.TT_S2.Sniper1_Cyan",
        "Exotic.TT_S2.Sniper1_Cyan.Exotic",
        "Exotic.TT_S2.Sniper1_Pink",
        "Exotic.TT_S2.Sniper1_Pink.Exotic",
        "Exotic.TT_S2.Sniper1_Theme1",
        "Exotic.TT_S2.Sniper1_Theme1.Exotic",
        "Exotic.TT_S2.Sniper1_Theme2",
        "Exotic.TT_S2.Sniper1_Theme2.Exotic",
        "Exotic.TT_S2.Sniper1_Theme3",
        "Exotic.TT_S2.Sniper1_Theme3.Exotic"
    },
    
    MeleeSkins = {
        "Exotic.RGB.Apocalypse.Chainsaw",
        "Exotic.RGB.Apocalypse.Chainsaw.Exotic",
        "Exotic.RGB.Apocalypse.Glove",
        "Exotic.RGB.Apocalypse.Glove.Exotic",
        "Exotic.RGB.Ashrend.Kukri",
        "Exotic.RGB.Ashrend.Kukri.Exotic",
        "Exotic.RGB.ClassKnife.Exotic",
        "Exotic.RGB.Eternium.FlipKnife",
        "Exotic.RGB.Eternium.FlipKnife.Exotic",
        "Exotic.RGB.Eternium.Glove",
        "Exotic.RGB.Eternium.Glove.Exotic",
        "Exotic.RGB.FlipKnife.Exotic",
        "Exotic.RGB.Fools2026.Lollipop",
        "Exotic.RGB.Fools2026.Lollipop.Exotic",
        "Exotic.RGB.Luna.ButterflyKnife",
        "Exotic.RGB.Luna.ButterflyKnife.Exotic",
        "Exotic.RGB.Luna.Glove",
        "Exotic.RGB.Luna.Glove.Exotic",
        "Exotic.RGB.NeonCore.Axe",
        "Exotic.RGB.NeonCore.Axe.Exotic",
        "Exotic.RGB.NeonCore.ButterflyKnife",
        "Exotic.RGB.NeonCore.ButterflyKnife.Exotic",
        "Exotic.RGB.NeonCore.Glove",
        "Exotic.RGB.NeonCore.Glove.Exotic",
        "Exotic.RGB.NeonCore.Wakizashi",
        "Exotic.RGB.NeonCore.Wakizashi.Exotic",
        "Exotic.RGB.NightHunt.CrookSword.Exotic",
        "Exotic.RGB.NightHunt.Glove.Exotic",
        "Exotic.RGB.Nya.ButterflyKnife.Exotic",
        "Exotic.RGB.Nya.Glove.Exotic",
        "Exotic.RGB.Nya.Karambit.Exotic",
        "Exotic.RGB.Nya.Wakizashi.Exotic",
        "Exotic.RGB.S4.VioletFiend.Glove.Exotic",
        "Exotic.RGB.S4.VioletFiend.Shovel.Exotic",
        "Exotic.RGB.S5.VioletFiend.Karambit.Exotic",
        "Exotic.RGB.ScalySawTeeth",
        "Exotic.RGB.ScalySawTeeth.Exotic",
        "Exotic.RGB.StarLord.Glove.Exotic",
        "Exotic.RGB.StarLord.Skeleton.Exotic",
        "Exotic.RGB.Starry.Axe",
        "Exotic.RGB.Starry.Axe.Exotic",
        "Exotic.RGB.Starry.Bayonet_M9",
        "Exotic.RGB.Starry.Bayonet_M9.Exotic",
        "Exotic.RGB.Starry.ButterflyKnife",
        "Exotic.RGB.Starry.ButterflyKnife.Exotic",
        "Exotic.RGB.Starry.CordKnife",
        "Exotic.RGB.Starry.CordKnife.Exotic",
        "Exotic.RGB.Starry.Glove",
        "Exotic.RGB.Starry.Glove.Exotic",
        "Exotic.RGB.Starry.Karambit",
        "Exotic.RGB.Starry.Karambit.Exotic",
        "Exotic.RGB.Starry.Kukri.Exotic",
        "Exotic.RGB.Starry.Wakizashi",
        "Exotic.RGB.Starry.Wakizashi.Exotic",
        "Exotic.RGB.Steam.Bayonet_M9",
        "Exotic.RGB.Steam.Bayonet_M9.Exotic",
        "Exotic.RGB.Steam.Glove",
        "Exotic.RGB.Steam.Glove.Exotic",
        "Exotic.RGB.TT_S1.Glove.Exotic",
        "Exotic.RGB.TT_S2.Glove.Exotic",
        "Exotic.RGB.TT_S2.PrismTwins.Exotic",
        "Exotic.RGB.Watcher.Glove",
        "Exotic.RGB.Watcher.Glove.Exotic",
        "Exotic.RGB.Watcher.Karambit",
        "Exotic.RGB.Watcher.Karambit.Exotic"
    }
}
